### ISSUE TITLE
use over-the-top srlinux configs

### ISSUE THREAD

**Issue by hellt** [srl-labs/nokia-evpn-lab#1]
Hi @bclasse 
please refactor the startup-config files to use add-on format instead of a full config file one.
By "add-on" I mean the CLI-styled config blobs of the config regions that you touched when creating a service.

Example for SRL: https://github.com/srl-labs/srl-telemetry-lab/blob/main/configs/fabric/leaf1.cfg

**Comment by bclasse** [comment]
Solved in 979a80c6558aad765b9c92a01832616c2b3ffeb2
